### ISSUE TITLE
Exception when DateTimeOffset property is used

### ISSUE THREAD

**Issue by JCKodel** [FastMapper/FastMapper#1]
Trying to map a class to another (class A inherits B, so all properties are equal), but 2 properties are DateTimeOffset.
While calling TypeAdapter<B>(instanceOfA):

GenericArguments[0], 'System.DateTimeOffset', on 'FastMapper.Adapters.ClassAdapter`2[TSource,TDestination]' violates the constraint of type parameter 'TSource'.

**Comment by azumelzu** [comment]
Same issue with TimeSpan:
TypeAdapter.Adapt<TimeSpan>(new TimeSpan()) throws the following exception:

TypeAdapter.Adapt<TimeSpan>(new TimeSpan()) | 'TypeAdapter.Adapt<TimeSpan>(new TimeSpan())' threw an exception of type 'System.ArgumentException' | System.TimeSpan {System.ArgumentException}

| Message | "GenericArguments[0], 'System.TimeSpan', on 'FastMapper.Adapters.ClassAdapter`2[TSource,TDestination]' violates the constraint of type parameter 'TSource'." | string

   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at FastMapper.TypeAdapter.GetAdapter(Type sourceType, Type destinationType, Boolean hasDestination)
   at FastMapper.TypeAdapter.Adapt[TDestination](Object source)
